"""Quality helpers for finalization metadata and key-metric fallbacks."""

import re
import zipfile
from typing import Any
from xml.etree import ElementTree

_DOCX_CORE_NAMESPACES = {
    "cp": (
        "http://schemas.openxmlformats.org/package/2006/"
        "metadata/core-properties"
    ),
    "dc": "http://purl.org/dc/elements/1.1/",
    "dcterms": "http://purl.org/dc/terms/",
}
_DOCX_SYNTHETIC_CREATORS = {"python-docx"}
_DATE_PATTERNS = [
    re.compile(r"Q[1-4]\s*20\d{2}", re.IGNORECASE),
    re.compile(r"20\d{2}-\d{2}-\d{2}"),
    re.compile(
        r"(?:January|February|March|April|May|June|July|August|"
        r"September|October|November|December)\s+20\d{2}",
        re.IGNORECASE,
    ),
    re.compile(r"FY\s*20\d{2}", re.IGNORECASE),
]
_VALUE_TOKEN = (
    r"[\$\£\€\¥C]?\$?\s*\d[\d,]*(?:\.\d+)?"
    r"(?:\s*(?:%|bp|bps|pt|pts|d|days|k|m|mm|b|bn)"
    r"(?![A-Za-z]))?"
)
_METRIC_RE = re.compile(
    r"([A-Z][A-Za-z0-9_ /&\-]{1,60}?)"
    r"\s*[:=]\s*"
    r"(" + _VALUE_TOKEN + r")"
    r"\s*(?:[).,;:]*)$",
    re.IGNORECASE,
)
_METRIC_AT_RE = re.compile(
    r"([A-Za-z][A-Za-z0-9_ /&\-\(\)]{1,60}?)"
    r"\s+at\s+"
    r"(" + _VALUE_TOKEN + r")"
    r"\s*(?:[).,;:]*)$",
    re.IGNORECASE,
)
_STRUCTURED_LABEL_HEADERS = {
    "metric",
    "metrics",
    "card",
    "cards",
    "kpi",
    "kpis",
    "label",
    "labels",
}
_STRUCTURED_VALUE_HEADERS = {
    "value",
    "values",
    "current",
    "current value",
    "amount",
}
_GENERIC_METRIC_LABELS = {
    "adverse",
    "base",
    "response",
    "severe",
    "value",
    "values",
    "retail",
    "commercial",
    "markets",
    "cards",
    "payments",
    "deposits",
    "other",
    "visuals",
    "second dense table",
    "mm range",
    "pct range",
    "stage values",
}
_NOISY_METRIC_LABEL_PATTERNS = (
    re.compile(r"\bformula region\b", re.IGNORECASE),
    re.compile(r"\bdense table\b", re.IGNORECASE),
    re.compile(r"\bexample rows\b", re.IGNORECASE),
    re.compile(r"\bkey table rows\b", re.IGNORECASE),
    re.compile(r"\bused range\b", re.IGNORECASE),
    re.compile(r"\bsheet name\b", re.IGNORECASE),
    re.compile(r"\bfile type\b", re.IGNORECASE),
    re.compile(r"\bcolumn headers\b", re.IGNORECASE),
)
_NOISY_METRIC_TERMS = {
    "appendix",
    "column",
    "columns",
    "currency",
    "currencies",
    "example",
    "examples",
    "grid",
    "listing",
    "page",
    "range",
    "record",
    "records",
    "region",
    "row",
    "rows",
    "scenario",
    "sheet",
    "symbol",
    "symbols",
    "table",
    "unicode",
    "worksheet",
}
_COUNT_METRIC_TERMS = (
    "backlog",
    "complaint",
    "complaints",
    "incident",
    "incidents",
    "record",
    "records",
    "case",
    "cases",
    "count",
    "rows",
)
_TRAILING_LABEL_QUALIFIERS = {
    "estimated",
    "estimate",
    "listed",
    "measured",
    "observed",
    "reported",
    "shown",
}


def _coerce_int(value: Any, default: int) -> int:
    """Convert a value to `int` or return the default."""
    try:
        return int(value)
    except (TypeError, ValueError):
        return default


def _page_metadata(page: dict[str, Any]) -> dict[str, Any]:
    """Return safe page metadata from an enrichment page."""
    metadata = page.get("metadata", {})
    if isinstance(metadata, dict):
        return dict(metadata)
    return {}


def _docx_core_text(root: ElementTree.Element, path: str) -> str:
    """Read one text field from DOCX core properties XML."""
    element = root.find(path, _DOCX_CORE_NAMESPACES)
    if element is None or element.text is None:
        return ""
    return element.text.strip()


def _extract_date_from_docx_metadata(file_path: str) -> str:
    """Read a non-synthetic publication date from DOCX metadata."""
    if not file_path.lower().endswith(".docx"):
        return ""

    try:
        with zipfile.ZipFile(file_path) as archive:
            core_xml = archive.read("docProps/core.xml")
    except (FileNotFoundError, KeyError, OSError, zipfile.BadZipFile):
        return ""

    try:
        root = ElementTree.fromstring(core_xml)
    except ElementTree.ParseError:
        return ""

    creator = _docx_core_text(root, "dc:creator").lower()
    description = _docx_core_text(root, "dc:description").lower()
    if (
        creator in _DOCX_SYNTHETIC_CREATORS
        or "generated by python-docx" in description
    ):
        return ""

    for path in ("dcterms:created", "dcterms:modified"):
        value = _docx_core_text(root, path)
        if re.match(r"20\d{2}-\d{2}-\d{2}", value):
            return value[:10]
    return ""


def _extract_date_from_content(pages: list[dict[str, Any]]) -> str:
    """Search page content for file-local date patterns."""
    for page in pages[:5]:
        text = " ".join(
            str(page.get(field, ""))
            for field in ("page_title", "summary", "content")
        )
        for pattern in _DATE_PATTERNS:
            match = pattern.search(text)
            if match:
                return match.group(0).strip()
    return ""


def _normalize_metric_label(label: str) -> str:
    """Normalize a metric label for matching."""
    return re.sub(r"\s+", " ", label.strip().strip(":;,.")).lower()


def _clean_metric_value(value: str) -> str:
    """Strip trailing punctuation from a metric value."""
    return value.strip().rstrip(".,;:")


def _canonical_metric_label(label: str) -> str:
    """Return a cleaned, display-ready metric label."""
    cleaned = re.sub(r"\s+", " ", label.strip().strip(":;,."))
    words = cleaned.split()
    while (
        words and words[-1].lower().rstrip(".") in _TRAILING_LABEL_QUALIFIERS
    ):
        words.pop()
    cleaned = " ".join(words).strip()
    if cleaned and cleaned.lower() == cleaned:
        return cleaned.capitalize()
    return cleaned


def _looks_like_sequence_value(value: str) -> bool:
    """Return whether a value looks like a metric series."""
    candidate = re.sub(
        r"^[\$\£\€\¥C]?\$?\s*|\s*(?:%|bp|bps|pt|pts|d|days|k|m|mm|b|bn)$",
        "",
        value.strip(),
        flags=re.IGNORECASE,
    )
    parts = [part for part in candidate.split(",") if part]
    if len(parts) <= 1:
        return False
    return not all(
        part.isdigit() and index > 0 and len(part) == 3
        for index, part in enumerate(parts)
    )


def _value_has_metric_unit(value: str) -> bool:
    """Return whether the value carries a meaningful unit marker."""
    return bool(
        re.search(
            r"[\$\£\€\¥]|(?:%|bp|bps|pt|pts|d|days|k|m|mm|b|bn)\b",
            value,
            re.IGNORECASE,
        )
    )


def _label_allows_plain_count(label: str) -> bool:
    """Return whether a plain integer is acceptable for the label."""
    normalized = _normalize_metric_label(label)
    if normalized.startswith("total "):
        return True
    return any(term in normalized for term in _COUNT_METRIC_TERMS)


def _is_usable_metric_pair(label: str, value: str) -> bool:
    """Apply quality guards to a candidate key-metric pair."""
    normalized_label = _normalize_metric_label(label)
    cleaned_value = _clean_metric_value(value)
    if not normalized_label or not cleaned_value:
        return False
    if normalized_label in _GENERIC_METRIC_LABELS:
        return False
    if any(
        pattern.search(normalized_label)
        for pattern in _NOISY_METRIC_LABEL_PATTERNS
    ):
        return False
    if any(term in normalized_label.split() for term in _NOISY_METRIC_TERMS):
        return False
    if _looks_like_sequence_value(cleaned_value):
        return False
    if re.fullmatch(r"\d+(?:\.\d+)?", cleaned_value) and not (
        _value_has_metric_unit(cleaned_value)
        or _label_allows_plain_count(normalized_label)
    ):
        return False
    return True


def _normalize_key_metrics(raw_metrics: Any) -> dict[str, str]:
    """Normalize a metric dict while filtering noisy entries."""
    if not isinstance(raw_metrics, dict):
        return {}
    normalized: dict[str, str] = {}
    seen_labels: dict[str, str] = {}
    for key, value in raw_metrics.items():
        label = _canonical_metric_label(str(key))
        metric_value = _clean_metric_value(str(value).strip())
        if _is_usable_metric_pair(label, metric_value):
            normalized_label = _normalize_metric_label(label)
            existing = seen_labels.get(normalized_label)
            if existing is not None:
                normalized.pop(existing, None)
            normalized[label] = metric_value
            seen_labels[normalized_label] = label
    return normalized


def _row_cells(row: dict[str, Any]) -> list[tuple[int, str]]:
    """Return ordered `(column, value)` cells for a region row."""
    cells = row.get("cells", [])
    if not isinstance(cells, list):
        return []
    ordered = []
    for cell in cells:
        if not isinstance(cell, dict):
            continue
        column = _coerce_int(cell.get("column_number"), 0)
        value = str(cell.get("value", "")).strip()
        if column > 0 and value:
            ordered.append((column, value))
    return sorted(ordered)


def _metric_header_columns(
    rows: list[dict[str, Any]],
) -> tuple[int, int, int] | None:
    """Locate a row with a label/value header pair."""
    for index, row in enumerate(rows[:3]):
        cells = _row_cells(row)
        if len(cells) < 2:
            continue
        header_values = [_normalize_metric_label(value) for _, value in cells]
        if (
            header_values[0] in _STRUCTURED_LABEL_HEADERS
            and header_values[1] in _STRUCTURED_VALUE_HEADERS
        ):
            return index, cells[0][0], cells[1][0]
    return None


def _extract_metrics_from_region_rows(rows: Any) -> dict[str, str]:
    """Extract metric pairs from typed XLSX region rows."""
    if not isinstance(rows, list):
        return {}
    header = _metric_header_columns(rows)
    if header is None:
        return {}

    header_index, label_column, value_column = header
    metrics: dict[str, str] = {}
    for row in rows[header_index + 1 :]:
        cells = dict(_row_cells(row))
        label = str(cells.get(label_column, "")).strip()
        value = str(cells.get(value_column, "")).strip()
        if not label or not value:
            continue
        if label.lower().startswith("narrative note"):
            continue
        label = _canonical_metric_label(label)
        cleaned_value = _clean_metric_value(value)
        if _is_usable_metric_pair(label, cleaned_value):
            metrics[label] = cleaned_value
    return metrics


def _split_pipe_cells(line: str) -> list[str]:
    """Split a pipe-delimited line into cells."""
    stripped = line.strip()
    if not stripped.startswith("|") or not stripped.endswith("|"):
        return []
    return [cell.strip() for cell in stripped.strip("|").split("|")]


def _extract_metrics_from_markdown_table(content: str) -> dict[str, str]:
    """Extract metric pairs from a markdown-style table."""
    lines = [line for line in content.splitlines() if "|" in line]
    for index in range(len(lines) - 2):
        header = _split_pipe_cells(lines[index])
        separator = _split_pipe_cells(lines[index + 1])
        if len(header) < 2 or len(separator) < 2:
            continue
        if not all(set(cell) <= {"-", ":"} for cell in separator if cell):
            continue
        normalized_header = [_normalize_metric_label(cell) for cell in header]
        if (
            normalized_header[0] not in _STRUCTURED_LABEL_HEADERS
            or normalized_header[1] not in _STRUCTURED_VALUE_HEADERS
        ):
            continue

        metrics: dict[str, str] = {}
        for line in lines[index + 2 :]:
            cells = _split_pipe_cells(line)
            if len(cells) < 2:
                break
            label = _canonical_metric_label(cells[0])
            value = _clean_metric_value(cells[1])
            if _is_usable_metric_pair(label, value):
                metrics[label] = value
        if metrics:
            return metrics
    return {}


def _extract_metrics_from_bulleted_cards(content: str) -> dict[str, str]:
    """Extract `label -> value` pairs from nested slide KPI-card bullets."""
    metrics: dict[str, str] = {}
    lines = content.splitlines()
    for index, raw_line in enumerate(lines):
        stripped = raw_line.strip()
        indent = len(raw_line) - len(raw_line.lstrip(" "))
        if indent != 0 or not stripped.startswith("- "):
            continue

        label = stripped[2:].strip()
        if not label or ":" in label:
            continue

        for nested_raw in lines[index + 1 :]:
            nested_stripped = nested_raw.strip()
            nested_indent = len(nested_raw) - len(nested_raw.lstrip(" "))
            if not nested_stripped:
                continue
            if nested_indent <= indent:
                break
            match = re.match(
                r"-\s*Value\s*:\s*(" + _VALUE_TOKEN + r")$",
                nested_stripped,
                re.IGNORECASE,
            )
            if match is None:
                continue
            value = _clean_metric_value(match.group(1))
            canonical_label = _canonical_metric_label(label)
            if _is_usable_metric_pair(canonical_label, value):
                metrics[canonical_label] = value
            break
    return metrics


def _extract_structured_metrics_from_pages(
    pages: list[dict[str, Any]],
    filetype: str,
) -> dict[str, str]:
    """Extract key metrics from structured page content."""
    metrics: dict[str, str] = {}
    for page in pages:
        metadata = _page_metadata(page)
        handling_mode = str(metadata.get("handling_mode", "")).strip()

        if filetype == "xlsx" and handling_mode == "page_like":
            dense_regions = metadata.get("dense_table_regions", [])
            if isinstance(dense_regions, list):
                for region in dense_regions:
                    if not isinstance(region, dict):
                        continue
                    metrics.update(
                        _extract_metrics_from_region_rows(
                            region.get("rows", [])
                        )
                    )

        content = str(page.get("content", ""))
        if content:
            metrics.update(_extract_metrics_from_markdown_table(content))
            if filetype == "pptx":
                metrics.update(_extract_metrics_from_bulleted_cards(content))
    return metrics


def _metric_clauses(text: str) -> list[str]:
    """Split text into conservative metric clauses."""
    split_clauses = re.split(r"[;\n]", text)
    expanded: list[str] = []
    for clause in split_clauses:
        expanded.extend(
            re.split(
                r",\s+(?=[A-Z][A-Za-z0-9_ /&\-\(\)]{1,60}\s*(?:[:=]|\bat\b))",
                clause,
            )
        )
    return [clause.strip(" -*") for clause in expanded if clause.strip()]


def _extract_metrics_from_text(texts: list[str]) -> dict[str, str]:
    """Extract conservative prose metric statements from summary text."""
    metrics: dict[str, str] = {}
    for text in texts:
        for clause in _metric_clauses(text):
            for pattern in (_METRIC_RE, _METRIC_AT_RE):
                match = pattern.match(clause)
                if match is None:
                    continue
                name = _canonical_metric_label(str(match.group(1)))
                value = _clean_metric_value(str(match.group(2)).strip())
                if _is_usable_metric_pair(name, value):
                    metrics[name] = value
                break
    return metrics
