from typing import Any

class Tools:
    def mupdf_display_errors(self, enabled: bool) -> None: ...
    def mupdf_warnings(self) -> None: ...

TOOLS: Tools

class Matrix:
    def __init__(self, x_scale: float, y_scale: float) -> None: ...

class IRect:
    def __init__(self, x0: int, y0: int, x1: int, y1: int) -> None: ...

class Pixmap:
    width: int
    height: int

    def __init__(self, *args: Any) -> None: ...
    def shrink(self, amount: int) -> None: ...
    def tobytes(self, format_name: str) -> bytes: ...

class Page:
    def get_pixmap(self, matrix: Matrix, alpha: bool) -> Pixmap: ...

class Document:
    page_count: int

    def load_page(self, index: int) -> Page: ...
    def close(self) -> None: ...

def open(path: str) -> Document: ...
